/*
*Claves e identificadores de cada uno de los dispositivos que creamos en la red Helium.
*DEVEUI APPEUI en LSB, APPKEY en MSB.
*/

#ifndef DISPOSITIVOS_H
#define DISPOSITIVOS_H

#define DEVEUI_DISPOSITIVO_00 0xFD, 0xA9, Copiar desde la consola de Helium en LSB...
#define APPEUI_DISPOSITIVO_00 0x21, 0xD3, Copiar desde la consola de Helium en LSB...
#define APPKEY_DISPOSITIVO_00 0x5A, 0x0E, Copiar desde la consola de Helium en MSB...

#define DEVEUI_DISPOSITIVO_01 0xB9, 0x5B, Copiar desde la consola de Helium en LSB...
#define APPEUI_DISPOSITIVO_01 0x21, 0xD3, Copiar desde la consola de Helium en LSB...
#define APPKEY_DISPOSITIVO_01 0x71, 0xA0, Copiar desde la consola de Helium en MSB......

#define DEVEUI_Sensor_Temperatura_00 0xE9, 0xBF, Copiar desde la consola de Helium en LSB...
#define APPEUI_Sensor_Temperatura_00 0x21, 0xD3, Copiar desde la consola de Helium en LSB...
#define APPKEY_Sensor_Temperatura_00 0xE8, 0xEA, Copiar desde la consola de Helium en MSB......

#endif